# Site settings
title: 前端自由者
email: yuhongfei1001@163.com
description: "最可怕的生活不是今天不知道明天怎样，而是现在就看到了自己一生的全部，而且无法改变。"
baseurl: ""
url: "http://farmanyu.github.io"

# Build settings
markdown: kramdown
permalink: pretty
