# Site settings
title: 前端自由者
subTitle: 热爱编程，希望编程可以改变以后每天的生活。
email: yuhongfei1001@163.com
description: "最可怕的生活不是今天不知道明天怎样，而是现在就看到了自己一生的全部，而且无法改变。"
baseurl: ""
url: "http://farmanyu.github.io"
feed: /feed.xml

# Build settings
markdown:   rdiscount
pygments:   true
paginate:   4

style:  /css/style.css
blogName:     
blogDesc: 
favicon:   /favicon.ico
theme:    blue

indexContent:     true
imageLink:        http://www.pizn.net/static/images/20121109Monutain.jpg

disqus:           piznblog

copyright:        Copyright © 2011-2012 Farman All rights reserved.            

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-list-ul
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: http://weibo.com/gghongfei
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/FarmanYu/farmanyu.github.com
    icon: icon-github
    class: none

page:
  - text: 我的作品
    url: /games.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: Farman
  email:   yuhongfei1001@163.com
  description:  "最可怕的生活不是今天不知道明天怎样，而是现在就看到了自己一生的全部，而且无法改变。"

duoshuo:
  config: true
  id: farman